Import Libraries

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler

Load Dataset

In [2]:
import pandas as pd

df = pd.read_csv(
    "../data/raw/bank-additional/bank-additional-full.csv",
    sep=";"
)

df.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

Remove Duplicate Rows

In [3]:
print("Before:", df.shape)

df = df.drop_duplicates()

print("After :", df.shape)

Before: (41188, 21)
After : (41176, 21)

Check Missing Values

In [4]:
df.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

Encode Target Variable

In [5]:
df["y"] = df["y"].map({
    "no": 0,
    "yes": 1
})

df["y"].value_counts()

y
0    36537
1     4639
Name: count, dtype: int64

Separate Features and Target

In [6]:
X = df.drop("y", axis=1)

y = df["y"]

print("Features Shape :", X.shape)
print("Target Shape   :", y.shape)

Features Shape : (41176, 20)
Target Shape   : (41176,)

Categorical Columns

In [7]:
categorical_cols = X.select_dtypes(include="object").columns.tolist()

print(categorical_cols)

['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'day_of_week', 'poutcome']

One-Hot Encoding

In [8]:
X = pd.get_dummies(
    X,
    drop_first=True
)

print("Encoded Features Shape:", X.shape)

Encoded Features Shape: (41176, 53)

Encoded Dataset

In [9]:
X.head()

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,...,month_may,month_nov,month_oct,month_sep,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_nonexistent,poutcome_success
0,56,261,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,True,False,False,False,True,False,False,False,True,False
1,57,149,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,True,False,False,False,True,False,False,False,True,False
2,37,226,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,True,False,False,False,True,False,False,False,True,False
3,40,151,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,True,False,False,False,True,False,False,False,True,False
4,56,307,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,True,False,False,False,True,False,False,False,True,False

Train Test Split

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training Features :", X_train.shape)
print("Testing Features  :", X_test.shape)

print("Training Target   :", y_train.shape)
print("Testing Target    :", y_test.shape)

Training Features : (32940, 53)
Testing Features  : (8236, 53)
Training Target   : (32940,)
Testing Target    : (8236,)

Feature Scaling

In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

Final Shapes

In [12]:
print("X_train :", X_train.shape)
print("X_test  :", X_test.shape)

print("y_train :", y_train.shape)
print("y_test  :", y_test.shape)

X_train : (32940, 53)
X_test  : (8236, 53)
y_train : (32940,)
y_test  : (8236,)

Saving Data

In [13]:
import os
import joblib

os.makedirs("../src/data/processed", exist_ok=True)

joblib.dump(X_train, "../src/data/processed/X_train.pkl")
joblib.dump(X_test, "../src/data/processed/X_test.pkl")
joblib.dump(y_train, "../src/data/processed/y_train.pkl")
joblib.dump(y_test, "../src/data/processed/y_test.pkl")

joblib.dump(scaler, "../src/data/processed/scaler.pkl")

print("Processed data saved successfully.")

Processed data saved successfully.

In [14]:
import joblib

joblib.dump(X.columns.tolist(), "../models/feature_names.pkl")

['../models/feature_names.pkl']

Remove Duration Feature

In [15]:
# Remove duration column
df = df.drop(columns=["duration"])

print("Duration feature removed successfully.\n")

print("Updated Dataset Shape:")
print(df.shape)

print("\nRemaining Columns:")
print(df.columns.tolist())

Duration feature removed successfully.

Updated Dataset Shape:
(41176, 20)

Remaining Columns:
['age', 'job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'day_of_week', 'campaign', 'pdays', 'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx', 'cons.conf.idx', 'euribor3m', 'nr.employed', 'y']

Handle Unknown Values

In [16]:
unknown_columns = [
    "job",
    "marital",
    "education",
    "default",
    "housing",
    "loan"
]

for col in unknown_columns:
    mode_value = df.loc[df[col] != "unknown", col].mode()[0]
    df[col] = df[col].replace("unknown", mode_value)

print("Unknown values handled successfully.\n")

for col in unknown_columns:
    print(f"{col}: {(df[col] == 'unknown').sum()} unknown values remaining")

Unknown values handled successfully.

job: 0 unknown values remaining
marital: 0 unknown values remaining
education: 0 unknown values remaining
default: 0 unknown values remaining
housing: 0 unknown values remaining
loan: 0 unknown values remaining

Save Clean Dataset

In [17]:
import os

os.makedirs("../src/data/processed", exist_ok=True)

df.to_csv(
    "../src/data/processed/bank_clean.csv",
    index=False
)

print("Clean dataset saved successfully.")
print("Location: ../src/data/processed/bank_clean.csv")

Clean dataset saved successfully.
Location: ../src/data/processed/bank_clean.csv

Final Dataset Information

In [18]:
print("FINAL DATASET INFORMATION")

print("\nDataset Shape:")
print(df.shape)

print("\nMissing Values:")
print(df.isnull().sum().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

FINAL DATASET INFORMATION

Dataset Shape:
(41176, 20)

Missing Values:
0

Duplicate Rows:
2097

Save Preprocessed Dataset

In [19]:
import os

os.makedirs("../src/data/processed", exist_ok=True)

df.to_csv(
    "../src/data/processed/bank_preprocessed.csv",
    index=False
)

print("Preprocessed dataset saved successfully.")
print("Location: ../src/data/processed/bank_preprocessed.csv")

Preprocessed dataset saved successfully.
Location: ../src/data/processed/bank_preprocessed.csv

Save Machine Learning Dataset

In [20]:
df.to_csv(
    "../src/data/processed/bank_ml_dataset.csv",
    index=False
)

print("Machine Learning dataset saved successfully.")

Machine Learning dataset saved successfully.

Preprocessing Summary

In [21]:
print("DATA PREPROCESSING COMPLETED")

print(f"Final Dataset Shape : {df.shape}")
print(f"Missing Values      : {df.isnull().sum().sum()}")
print(f"Duplicate Rows      : {df.duplicated().sum()}")

DATA PREPROCESSING COMPLETED
Final Dataset Shape : (41176, 20)
Missing Values      : 0
Duplicate Rows      : 2097

Final Machine Learning Dataset

In [22]:
X["y"] = y.values

X.to_csv(
    "../src/data/processed/bank_ml_dataset.csv",
    index=False
)

print("Machine Learning Dataset Saved Successfully.")
print(X.shape)

Machine Learning Dataset Saved Successfully.
(41176, 54)