Import Libraries

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

import warnings
warnings.filterwarnings("ignore")

Load Final Machine Learning Dataset

In [2]:
df = pd.read_csv("../src/data/processed/bank_ml_dataset.csv")

print("Dataset Loaded Successfully.\n")
print("Dataset Shape :", df.shape)

df.head()

Dataset Loaded Successfully.

Dataset Shape : (41176, 54)

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,...,month_nov,month_oct,month_sep,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_nonexistent,poutcome_success,y
0,56,261,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,False,False,False,True,False,False,False,True,False,0
1,57,149,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,False,False,False,True,False,False,False,True,False,0
2,37,226,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,False,False,False,True,False,False,False,True,False,0
3,40,151,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,False,False,False,True,False,False,False,True,False,0
4,56,307,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,False,False,False,True,False,False,False,True,False,0

Split Features and Target

In [3]:
X = df.drop("y", axis=1)
y = df["y"]

print("Features Shape :", X.shape)
print("Target Shape   :", y.shape)

Features Shape : (41176, 53)
Target Shape   : (41176,)

Train Test Split

In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training Features :", X_train.shape)
print("Testing Features  :", X_test.shape)

print("Training Target :", y_train.shape)
print("Testing Target  :", y_test.shape)

Training Features : (32940, 53)
Testing Features  : (8236, 53)
Training Target : (32940,)
Testing Target  : (8236,)

Verify Dataset

In [5]:
print("Advanced Machine Learning Dataset Ready")

print("Training Samples :", len(X_train))
print("Testing Samples  :", len(X_test))

print("\nTarget Distribution")
print(y.value_counts())

Advanced Machine Learning Dataset Ready
Training Samples : 32940
Testing Samples  : 8236

Target Distribution
y
0    36537
1     4639
Name: count, dtype: int64

XGBoost Classifier

In [6]:
xgb_model = XGBClassifier(
    random_state=42,
    eval_metric="logloss"
)

xgb_model.fit(X_train, y_train)

print("XGBoost Model Trained Successfully.")

XGBoost Model Trained Successfully.

XGBoost Evaluation

In [7]:
xgb_pred = xgb_model.predict(X_test)

accuracy_xgb = accuracy_score(y_test, xgb_pred) * 100
precision_xgb = precision_score(y_test, xgb_pred) * 100
recall_xgb = recall_score(y_test, xgb_pred) * 100
f1_xgb = f1_score(y_test, xgb_pred) * 100
roc_auc_xgb = roc_auc_score(y_test, xgb_pred) * 100

print(f"Accuracy : {accuracy_xgb:.2f}%")
print(f"Precision: {precision_xgb:.2f}%")
print(f"Recall   : {recall_xgb:.2f}%")
print(f"F1 Score : {f1_xgb:.2f}%")
print(f"ROC AUC  : {roc_auc_xgb:.2f}%")

print("\nClassification Report")
print(classification_report(y_test, xgb_pred))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, xgb_pred))

Accuracy : 91.49%
Precision: 63.96%
Recall   : 56.03%
F1 Score : 59.74%
ROC AUC  : 76.01%

Classification Report
              precision    recall  f1-score   support

           0       0.95      0.96      0.95      7308
           1       0.64      0.56      0.60       928

    accuracy                           0.91      8236
   macro avg       0.79      0.76      0.77      8236
weighted avg       0.91      0.91      0.91      8236


Confusion Matrix
[[7015  293]
 [ 408  520]]

LightGBM Classifier

In [8]:
lgb_model = LGBMClassifier(
    random_state=42
)

lgb_model.fit(X_train, y_train)

print("LightGBM Model Trained Successfully.")

[LightGBM] [Info] Number of positive: 3711, number of negative: 29229
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002252 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 759
[LightGBM] [Info] Number of data points in the train set: 32940, number of used features: 51
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.112659 -> initscore=-2.063860
[LightGBM] [Info] Start training from score -2.063860
LightGBM Model Trained Successfully.

LightGBM Evaluation

In [9]:
lgb_pred = lgb_model.predict(X_test)

accuracy_lgb = accuracy_score(y_test, lgb_pred) * 100
precision_lgb = precision_score(y_test, lgb_pred) * 100
recall_lgb = recall_score(y_test, lgb_pred) * 100
f1_lgb = f1_score(y_test, lgb_pred) * 100
roc_auc_lgb = roc_auc_score(y_test, lgb_pred) * 100

print(f"Accuracy : {accuracy_lgb:.2f}%")
print(f"Precision: {precision_lgb:.2f}%")
print(f"Recall   : {recall_lgb:.2f}%")
print(f"F1 Score : {f1_lgb:.2f}%")
print(f"ROC AUC  : {roc_auc_lgb:.2f}%")

print("\nClassification Report")
print(classification_report(y_test, lgb_pred))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, lgb_pred))

Accuracy : 91.69%
Precision: 64.99%
Recall   : 57.00%
F1 Score : 60.73%
ROC AUC  : 76.55%

Classification Report
              precision    recall  f1-score   support

           0       0.95      0.96      0.95      7308
           1       0.65      0.57      0.61       928

    accuracy                           0.92      8236
   macro avg       0.80      0.77      0.78      8236
weighted avg       0.91      0.92      0.91      8236


Confusion Matrix
[[7023  285]
 [ 399  529]]

CatBoost Classifier

In [10]:
cat_model = CatBoostClassifier(
    random_state=42,
    verbose=0
)

cat_model.fit(X_train, y_train)

print("CatBoost Model Trained Successfully.")

CatBoost Model Trained Successfully.

CatBoost Evaluation

In [11]:
cat_pred = cat_model.predict(X_test)

accuracy_cat = accuracy_score(y_test, cat_pred) * 100
precision_cat = precision_score(y_test, cat_pred) * 100
recall_cat = recall_score(y_test, cat_pred) * 100
f1_cat = f1_score(y_test, cat_pred) * 100
roc_auc_cat = roc_auc_score(y_test, cat_pred) * 100

print(f"Accuracy : {accuracy_cat:.2f}%")
print(f"Precision: {precision_cat:.2f}%")
print(f"Recall   : {recall_cat:.2f}%")
print(f"F1 Score : {f1_cat:.2f}%")
print(f"ROC AUC  : {roc_auc_cat:.2f}%")

print("\nClassification Report")
print(classification_report(y_test, cat_pred))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, cat_pred))

Accuracy : 91.63%
Precision: 65.58%
Recall   : 54.20%
F1 Score : 59.35%
ROC AUC  : 75.30%

Classification Report
              precision    recall  f1-score   support

           0       0.94      0.96      0.95      7308
           1       0.66      0.54      0.59       928

    accuracy                           0.92      8236
   macro avg       0.80      0.75      0.77      8236
weighted avg       0.91      0.92      0.91      8236


Confusion Matrix
[[7044  264]
 [ 425  503]]

Advanced Models Comparison

In [12]:
comparison = pd.DataFrame({

    "Model":[
        "XGBoost",
        "LightGBM",
        "CatBoost"
    ],

    "Accuracy (%)":[
        accuracy_xgb,
        accuracy_lgb,
        accuracy_cat
    ],

    "Precision (%)":[
        precision_xgb,
        precision_lgb,
        precision_cat
    ],

    "Recall (%)":[
        recall_xgb,
        recall_lgb,
        recall_cat
    ],

    "F1 Score (%)":[
        f1_xgb,
        f1_lgb,
        f1_cat
    ],

    "ROC AUC (%)":[
        roc_auc_xgb,
        roc_auc_lgb,
        roc_auc_cat
    ]

})

comparison

,Model,Accuracy (%),Precision (%),Recall (%),F1 Score (%),ROC AUC (%)
0,XGBoost,91.488587,63.960640,56.034483,59.735784,76.012589
1,LightGBM,91.694998,64.987715,57.004310,60.734788,76.552237
2,CatBoost,91.634288,65.580183,54.202586,59.351032,75.295053

Save Comparison Results

In [13]:
comparison.to_csv(
    "../reports/model_comparison_advanced.csv",
    index=False
)

print("Advanced Model Comparison Saved Successfully.")

Advanced Model Comparison Saved Successfully.

Best Advanced Model

In [14]:
best_model = comparison.loc[
    comparison["Accuracy (%)"].idxmax()
]

print("BEST ADVANCED MODEL")

print(best_model)

BEST ADVANCED MODEL
Model             LightGBM
Accuracy (%)     91.694998
Precision (%)    64.987715
Recall (%)        57.00431
F1 Score (%)     60.734788
ROC AUC (%)      76.552237
Name: 1, dtype: object

Model Building Summary

In [15]:
print("ADVANCED MODEL BUILDING COMPLETED")

print(f"XGBoost Accuracy  : {accuracy_xgb:.2f}%")
print(f"LightGBM Accuracy : {accuracy_lgb:.2f}%")
print(f"CatBoost Accuracy : {accuracy_cat:.2f}%")

ADVANCED MODEL BUILDING COMPLETED
XGBoost Accuracy  : 91.49%
LightGBM Accuracy : 91.69%
CatBoost Accuracy : 91.63%